### ISSUE TITLE
Delete "Learn More"

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1347]
## Context & versions

https://dev-sanchonet.govtool.byron.network/

## Actual behavior

![Image](https://github.com/IntersectMBO/govtool/assets/158469375/d81205e1-1240-4128-a3f2-a9c9b84ebf26)

## Expected behavior
Delete "Learn More" and add **View Proposals**

**Comment by vpaunovic** [comment]
@ValMBO This is also on GovTool side, not pdf side

**Comment by teske00** [comment]
@MSzalowski

**Comment by MSzalowski** [comment]
This is on GovTool side, and we have it in our designs - [ref](https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?node-id=8111-43534&t=e4KIWY2C9e2aPxET-4)

@m-i-k-e Should we change that button?

**Comment by l-br1** [comment]
@MSzalowski so that box on your side was originally designed for the governance action submission process, no that we integrate proposal discussion we need adjust it so that users can 'connect to propose' and 'view proposals' (second one like governance actions list doesn't require connecting the wallet).

figma wise we should update it on both sides

**Comment by MSzalowski** [comment]
Done with #1431

**Comment by pmbinapps** [comment]
OK NOW with button, leads to PDF



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/df8b7a66-5621-43b3-9810-e57b4dc71127)

**Comment by bosko-m** [comment]
This is now on Sancho, verified.
