### ISSUE TITLE
Back Option

### ISSUE THREAD

**Issue by ValMBO** [IntersectMBO/govtool#1423]
## Context & versions

https://dev-sanchonet.govtool.byron.network/proposal_pillar/proposal_discussion/304

## Actual behavior

The browser's back button isn't navigating me backward, but selecting "Show all" does restore previous navigation functionality.

## Expected behavior

Browser's back button should be in sync with show all

**Comment by pmbinapps** [comment]
FYI, Spotted it's not working on dev yet, https://jam.dev/c/71ccf0be-4d1a-4e06-94ee-e87bc0d6295b

**Comment by bosko-m** [comment]
@pmbinapps I've tested with the following and it works:
https://dev-sanchonet.govtool.byron.network/proposal_discussion/342 
https://dev-sanchonet.govtool.byron.network/proposal_discussion/306 

This bug was about browser back functionality when you are on proposal details page, not the page for all proposals. Furthermore, there is no Back to Proposal Discussion link anymore. And I cant see that link on Sancho, nor staging. Strange, can you verify the version you are testing or can you retest?

**Comment by teske00** [comment]
This is because this is not a new page at the browser level, but the same page with a different view at the application level cc @vpaunovic

**Comment by vpaunovic** [comment]
@kneerose It can be tested on dev.

 CC: @bosko-m

**Comment by bosko-m** [comment]
Tested, closing.
