### ISSUE TITLE
💡 CIP-119 DRep metadata images, reading and writing

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1806]
### Area

Delegation Pillar

### Is there new design needed?

Yes

### What?

- GovTool does not support writing or reading DRep images via CIP119 metadata
- It would be good to support this

[Related issue](https://github.com/IntersectMBO/govtool/issues/1762)

### Why?

- GovTool should follow the ecosystem standards

### How?

- Redesign the DRep reg and update form to allow image upload
- Redesign the DRep directory to show images

### (Optional) User Story with acceptance criteria

As a ada holder
I want to be able to see pictures uploaded via DRep metadata
then I can more easily differentiate between DReps at delegation time

**Comment by m-i-k-e** [comment]
A summary of what I found when testing:

1. Bug: If I enter a description and not a link, the form submits anyways (should error check that a link was added for every description: https://www.loom.com/share/6cfdd4287b3a432198ee58d86d2a96c8. However, the impact is lessened by the fact that the DRep screen following doesn't display blank "description" fields: https://www.loom.com/share/94e3277dc15c4b1da2aeccc5563766e6?sid=a7565e1b-1d19-4f8d-8ca4-5a5db294e412
2. Four issues in this video: https://www.loom.com/share/ba7a06f37f6d4eab8f47b115121cdbdb?sid=64753f9c-49ba-41f8-87cd-0786a5f13083
- The Delegate button shows on the DRep profile page, but shouldn't, as this DRep is me and I have delegated to myself
- The Drep profile page should show that I have delegated my own ADA to this DRep and it does not. This page is _misssing_ from the design file, i.e. it has not been done, and we need a new page for it.
- The Dashboard shows a confusing message in the Direct Voter card. It tells me that "I can't vote", but this is not true, as I can vote, just not as a Direct Voter. This needs addressing as a design issue as well. In total, we need to construct a table of what Dashboard card says what in all the possible scenarios.
- On the Dashboard, inside the DRep card, the DRep name is missing. 
3. Confusing interface due to a design decision: https://www.loom.com/share/4c974de0c8f143a98529e663f78091c9?sid=22bdf60b-4ca7-4081-a8fb-d13114b92f33
I've just delegated to a DRep, but the DRep's Voting power says Zero. I know we decided to only assess DRep Voting Power at epoch boundaries, but this video shows how that decisions negatively impacts the experience. Most users will think there is a bug in the system, as their chosen DRep's Voting Power is expected to increase by the value of their delegation. I can't imagine that many people will want to wait to the epoch boundary to see if their VP has been included.

In the same video, the DRep name is missing from the Drep list

4. Voting Power messages again confusing in Dashboard: https://www.loom.com/share/5bd75cc661a84236ab06ac497a13fbb6?sid=dc557dd7-9f0a-4b80-9061-3e21f7270435

5. Changing to Direct Voter from Delegate shows you are still delegated on Dashboard, until manual refresh https://www.loom.com/share/5e41d840076e4951bd7d9590b77f3d89?sid=19e66599-e5a5-4649-8d47-f8baf74f3408 See Video!

6. Changing to DRep from Direct Voter shows that I'm 'retired' as Direct Voter. This is confusing. https://www.loom.com/share/3adf3e0a93bf42d1ba1a38ef23920ae9?sid=2a7610dd-0446-4673-bf35-32b3d7ed42a4

**Comment by MSzalowski** [comment]
@m-i-k-e Would it be okay to fix these bugs while implementing the support for DRep images? Or should we split your comment into separate issues and fix it under the scope of these new issues?

**Comment by m-i-k-e** [comment]
This is ready for dev: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=16430-148267&t=8SB5qkNrX94NfBO6-1
