### ISSUE TITLE
🐛 Missing context for proposing treasury actions

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1837]
### Area

Proposal Pillar

### Domain

preview.gov.tools

### Context

When creating a treasury proposal, the on-chain details inputs miss context

### Steps to reproduce

Propose a treasury withdrawal

### Actual behavior

- The receiving address field, does not mention that the address is a Rewards Address (`stake1upe8zh...`)
- The amount field does not mention that the amount is in Ada

### Expected behavior

- The receiving address input box indicates that this is for a rewards/stake address
- The amount filed indicates the unit of ada

**Comment by vpaunovic** [comment]
@Ryun1 Can you explain a bit more maybe (maybe I am missing some context what is wrong and what needs to be done and in what way)? Because we have a error message `It must be reward address in bech32 format`  if the address is not the reward address in bech32 format.. also for amount we have validations and error messages for them (`Only number is allowed`, `Only positive number is allowed`). Everything other is like it was in design

**Comment by Ryun1** [comment]
Yeah there is quite a few tweaks i would like to do to the designs for this...
- see https://github.com/IntersectMBO/pdf-ui/pull/127

**Comment by vpaunovic** [comment]
In that [PR](https://github.com/IntersectMBO/pdf-ui/pull/127) from above we have this info that will be done.
`titleMaxLength = 80`
`abstractMaxLength = 2500`
`motivationRationaleMaxLength = 12000`
