### ISSUE TITLE
🐛 Cannot view on-chain governance action details when metadata incorrect

### ISSUE THREAD

**Issue by Ryun1** [IntersectMBO/govtool#1889]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Context

- Parameter change and hardfork actions have the possibility to show the on-chain details
- The details tab is only shown when the off-chain metadata is correct
- The details tab should be able to be accessed even when metadata is incorrect

incorrect metadata (no details)
![image](https://github.com/user-attachments/assets/eadd9b3d-bfed-4793-a24f-cf34a77594a6)

details (parameters) tab
![image](https://github.com/user-attachments/assets/329a95f7-68e5-4dbb-ac52-34c2fa5b9c24)

### Steps to reproduce

1. look at a parameter change or HF GA that has incorrect metadata
 

### Actual behavior

The on-chain details cannot be accessed when metadata incorrect

### Expected behavior

The on-chain details can be accessed when metadata incorrect

**Comment by m-i-k-e** [comment]
@ryan 

To answer your question: The it should show the details when the metadata is missing or bad. 

The top screen is 100% wrong, and I think I raised a bug for it. In the top screen, the "View External Data" can't be done because: It's not found. So it's just plain wrong. 

The bottom screen looks correct.What shows under the 'Reasoning' tab is what you would get with a non-tabbed page: I.e. if the data was missing, it would say so under that tab, as that is the same content as in a non-tabbed page. So, if the data is missing, it would say that under that tab, but the parameters would be visible under the parameters tab. 

This is not the only way to slice this, but when there is metadata, it qualifies as the 'reasoning' of the GA.We rushed this design, as everything is rushed now, and didn't look at the implications of adding a tab on the pages that didn't need tabs. But I think it isn't really broken.

**Comment by MSzalowski** [comment]
So if the metadata is incorrect - instead of displaying tabs it should be just label `Parameters` with the content below?

**Comment by MSzalowski** [comment]
@m-i-k-e Should the `See external data` button be hidden only when the `Data Missing` validation error occurs or for every other validation error as well?

**Comment by Ryun1** [comment]
> @Ryun1 So if the metadata is incorrect - instead of displaying tabs it should just label Parameters with the content below?

Yup this sounds good

> @m-i-k-e Should the See external data button be hidden only when the Data Missing validation error occurs or for every other validation error as well?

IMO we should ALWAYS show the `See external data` button
for all error cases AND when metadata is valid

It is very useful for debugging and lets voters check where the GA author has stored the data 

Agreed @m-i-k-e ?

**Comment by m-i-k-e** [comment]
So @Ryun1 I think we talked about this before, and didn't come to any conclusion. Isn't there a security issue if someone puts something untoward on the external link - this could be a deliberate attempt to scam or spam someone.

You are saying that there's value in showing the data, and I can see your point, but only if it is metadata. We could do some checking on the url to see if it is json-like, I suppose, and this would remove a lot of threat and possible unpleasantness.

That would be my opinion. Show the data, but do some basic checks to see if it's ok. 

As far as "Data Missing" this means that the URL has not resolved. We can't sent people to that location, so the "External Data" link has to be disappeared on that one.

**Comment by m-i-k-e** [comment]
@Ryun1 After a bit of thought, I'm going to get designers to look at combining the two designs. Maybe it will be simpler than I first suggested. I will post the results to this issue.

**Comment by Ryun1** [comment]
@m-i-k-e 

> As far as "Data Missing" this means that the URL has not resolved. We can't sent people to that location, so the "External Data" link has to be disappeared on that one.

I think in this case it would still be nice to direct people to a 404 error, as it makes it obvious what the issue is and is just more consistent

> So @Ryun1 I think we talked about this before, and didn't come to any conclusion. Isn't there a security issue if someone puts something untoward on the external link - this could be a deliberate attempt to scam or spam someone.

yeah I am not sure that this is really an issue, we do warn people before redirecting them
