### ISSUE TITLE
DRep directory - DReps list

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#220]
[Link to figma](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=7824-119166&mode=design&t=KTLDNrZe8vSXCxAr-4)

Screenshot from figma
![dRep list + My drep](https://github.com/IntersectMBO/govtool/assets/24510246/01f64f5f-66ff-4b88-b505-b1e509c3c5cc)

This task should cover
Everything below filters which are:
* Drep item
* Copy to clipboard
* Voting power
* Status
* View details button
* Delegate button

**Comment by pmbinapps** [comment]
Drep list empty. Transactions not enabled yet.

**Comment by pmbinapps** [comment]
TO CHECK: text that user is registered as DRep - OK
OK - status update after Retirement


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/d85359ec-e2e2-4aef-9c06-8d425b625562)

OK - Filtering, Sorting as by design

NOTE: missing attributes used in sorting in GUI design eg Registration date, only one direction of Ordering values


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6df189e4-f86e-46ff-808a-f999bcfccbc3)

**Comment by pmbinapps** [comment]
Move back to QA as - Sticking card when user is Drep is not implemented

![image](https://github.com/IntersectMBO/govtool/assets/82152577/2334af77-c3d5-4166-810d-4f07940677f5)
