### ISSUE TITLE
🐛 ADA quantities format incorrect on Governance Actions

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#2305]
### Area

Other

### Domain

preview.gov.tools

### Which wallet were you using?

Latest Lace

### Context

I am looking at a vote on governance. The numbers are very long after the decimal point. Also, there is no comma separator.

<img width="1215" alt="image" src="https://github.com/user-attachments/assets/27e07cdb-1d76-4907-835c-eb6b2b8975d7">

### Steps to reproduce

Go to GA that has vote on it
Look at numbers

### Actual behavior

Numbers display with six decimal places and no comma separators

### Expected behavior

Numbers don't have any decimal part (they are rounded to the nearest ADA), and the ADA values are comma seperated.

**Comment by m-i-k-e** [comment]
Also, the numbers shouldn't be in bold. Please see this page in Figma: https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=14736-93156&t=xaC11CQKDDby1Wbv-1

**Comment by HeptaSean** [comment]
Don't know if it's too late, but I would ask to please do _not_ use a comma as thousands separator, but a space or thin space. Comma is very irritating internationally, especially where comma is used as decimal separator.

Although I would leave in the Lovelace exact values (why hide information?), but right-align and mono-space the whole thing, so that it can be easily grasped.

**Comment by bosko-m** [comment]
@MSzalowski Verified on Preview, however, raised another issue to now show thousands if its zero - #2372. Was observed on SPO part.
So **0,000** should become just **0**.
