### ISSUE TITLE
💡 Expand DRep directory list with additional useful information

### ISSUE THREAD

**Issue by bosko-m** [IntersectMBO/govtool#2334]
### Area

Delegation Pillar

### Is there new design needed?

Yes

### What?

When the delegator visits govtool or 1694.io, they will see a list of "DRep ID", "Name", and "Delegation amount".

Of course, the delegator can click to display details, but I don't think it's a good idea in terms of UI to have to click on hundreds of DReps from the top to display details.

### Why?

The problem is that the delegator cannot make any judgments by looking at this list.

### How?

I would appreciate it if you could select motivations, qualifications, etc. and display them in a list.

![download (3)](https://github.com/user-attachments/assets/01f18463-6e77-44a9-818c-40db76ab9b91)

**Comment by m-i-k-e** [comment]
@bosko-m If you are asking for a table that shows everything on the detail page, it is not possible. Well, it is possible, but it would not be usable to show all the drep info in one table. This is why we have a two tier solution. The same principle applies to something like amazon, ebay, etc. You do not see all the product's info in the search results because there is not enough room.
