### ISSUE TITLE
[USERSNAP] Tried to upload file to github and it couldn't verify it. https://github.com/cryptokyle79/CryptoKyle-Cardano-DRep/blob/main/CryptoKyle.jsonld

### ISSUE THREAD

**Issue by kickloop** [IntersectMBO/govtool#2359]
**Taken at**: https://gov.tools/register_drep
**Fields**:
- Add a comment: Tried to upload file to github and it couldn&#39;t verify it. https://github.com/cryptokyle79/CryptoKyle-Cardano-DRep/blob/main/CryptoKyle.jsonld

**Browser**: Chrome 130 (Windows 10)
**Screen size**: 1920x1080
**[Open #164 in Usersnap](https://app.usersnap.com/l/feedback/486fb0ee-90ac-4132-9c32-25256487adad?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by spannercode** [comment]
The issue is likely that the link isn’t a raw GitHub URL. It would be helpful to detect this and notify the user if their link isn’t in the correct format, prompting them to enter the raw URL instead.

**Comment by bosko-m** [comment]
Its tru its because of not using raw GitHub URL.
So the correct link, in case CryptoKyle99 sees this is:
https://raw.githubusercontent.com/cryptokyle79/CryptoKyle-Cardano-DRep/refs/heads/main/CryptoKyle.jsonld
Also covered in the documentation - https://docs.gov.tools/about/what-is-cardano-govtool/govtool-functions/dreps/register-as-a-drep
