### ISSUE TITLE
🐛  Incorrect Delegated Voting Power Display

### ISSUE THREAD

**Issue by kneerose** [IntersectMBO/govtool#2410]
### Area

Voting Pillar

### Domain

preview.gov.tools

### Which wallet were you using?

Eternl 1.12.16

### Context

I encountered an issue while attempting to delegate my voting power to "Abstain" , "Signal No Confidence." or any registered dRep. The displayed delegated voting power was inaccurate compared to my actual voting power.

### Steps to reproduce

1. Connect your wallet.
2. Delegate your voting power to "Abstain" , "Signal No Confidence." or any dRep listed on dRep directory
3. Observe the displayed delegated voting power.

### Actual behavior

 **Address details**: https://preview.cardanoscan.io/address/addr_test1qplfr7vedl9mr9yz0tfjs7qhzl0p0yjgsr4er6nyyyvddl0knh8y8zz88gnv7wtncztl60lpzryemsyn63uu2rduffvs58dgw5
- The displayed delegated voting power for "Abstain" and "Signal No Confidence" is incorrect.

![image](https://github.com/user-attachments/assets/cf2708ff-55b4-402f-9e18-94dfc2df93da)
![image](https://github.com/user-attachments/assets/4749f5dc-4bdb-4ba5-a7dc-7af6fe3edaea)

### Expected behavior

- The displayed delegated voting power should accurately reflect the actual voting power.

### Allure Report Links
- [2U. Should show delegated voting power for Abstain](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/203/#behaviors/cf5972b1ff6a9dad51740e455b7d5ef3/2a0d664460c36071/)
- [2V. Should show delegated voting power for No Confidence](https://intersectmbo.github.io/govtool-test-reports/govtool-frontend/200//#testresult/6ba0c36b526f4d9e)

### Similar Ticket
https://github.com/IntersectMBO/govtool/issues/1097

**Comment by MSzalowski** [comment]
GovTool v1.0.28 already includes fix for that issue.

Voting power delegated to any of abstain or no confidence is the voting power that ada holder controls (by its stake key).

Tested multiple stake keys comparing GovTool and cexplorer and in every case they were valid (*in my local env*).

Regarding the total amount of the Abstain and No confidence voting power - these two values are also completely equal to what cexplorer shows (compare two screens from preview below):
![Image](https://github.com/user-attachments/assets/2b39654d-d391-4eb9-8ba8-be0984309862)
![Image](https://github.com/user-attachments/assets/f28cb468-3415-4c36-b49c-204cb58ab940)


Which means that if there are any inconsistencies between these values they are caused by wrong records in utxo_view table in db-sync and It might need resyncing to show the proper values.

**Comment by kneerose** [comment]
@MSzalowski , the voting power is now correct on both the preview and dev environments. It seems this issue has been resolved. 
CC: @bosko-m
