### ISSUE TITLE
Display sole voter in drep explorer via DRep ID

### ISSUE THREAD

**Issue by MSzalowski** [IntersectMBO/govtool#318]
### Why

As a Sole Voter,

The only way someone can find me in the DRep Explorer is by searching for my exact DRep ID

So that I can allow only close friends and relatives to find and delegate to me

### What

1. Given that I am on the DRep Explorer page
When I enter a full, valid DRep ID of a registered Sole Voter
Then I will have the option of delegating to them

2. Given that I am on the DRep Explorer page
When I enter a valid DRep ID of a registered Sole Voter
Then I will not be able to click through to a profile page for this Sole Voter

### How

List Sole voter after directly providing DRep ID in a search

**Comment by pmbinapps** [comment]
Seems to be invalid state of Sole Voter and thus showing him on DRep list:

![image](https://github.com/IntersectMBO/govtool/assets/82152577/1d09ec17-a822-4315-8fd4-544648714f84)
![image](https://github.com/IntersectMBO/govtool/assets/82152577/5b898859-ff3c-4f4b-a116-3f6d1e4ac538)

**Comment by pmbinapps** [comment]
Why
As a Sole Voter,
@MSzalowski please take look if below is still valid
**TO CLARIFY** - The only way someone can find me in the DRep Explorer is by searching for my exact DRep ID


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e7e6cbd5-67d8-4996-b594-9ac2a70d6b1a)



So that I can allow only close friends and relatives to find and delegate to me

What
OK  Given that I am on the DRep Explorer page
        When I enter a full, valid DRep ID of a registered Sole Voter
        Then I will have the option of delegating to them - OK



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b7ef5848-9315-4ca3-81d9-b58a244e1c1b)


**TO CLARIFY:** - @MSzalowski please take look if below is still valid
            Given that I am on the DRep Explorer page
            When I enter a valid DRep ID of a registered Sole Voter
            **Then I will not be able to click through to a profile page for this Sole Voter**


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f62e3186-9c91-4d2f-a665-bce4c11e1272)



How
OK List Sole voter after directly providing DRep ID in a search - Sole voter - is being found.

**Comment by pmbinapps** [comment]
New issue appeared with Direct Voter not found when user registred as Direct Voter is performing search - tracked [here](https://github.com/IntersectMBO/govtool/issues/960) 


If other user is Searching then Direct Voter is found, and below is OK NOW:
OK: - @MSzalowski please take look if below is still valid
Given that I am on the DRep Explorer page
When I enter a valid DRep ID of a registered Sole Voter
Then I will not be able to click through to a profile page for this Sole Voter

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/62a6ee9d-f282-41b3-b695-30f062396a09)

**Comment by MSzalowski** [comment]
Based on the issue description it is valid
