### ISSUE TITLE
GA - Details - Voting - error appear when voting

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#855]
Occurred on test-sancho (affects other envs too) with Eternl(beta) wallet, when voting Yes on item:

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/f9062cb8-3f98-499e-8013-22920c26f034)

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/dc2765a2-3a20-4ad4-a52f-f786b70c5d73)

**Comment by pmbinapps** [comment]
Depends on Eterl (beta) wallet. Re-check if long error msg are fitting into error modal

**Comment by pmbinapps** [comment]
View OK now:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/6f0800e9-2795-49b5-99c3-a62ab52f76a3)

**Comment by m-i-k-e** [comment]
@l-br1 Not sure why you assigned this to me.

**Comment by m-i-k-e** [comment]
So I did this test using Demos 1.8.1 -

1. re-register as a Drep (successful)
2. Found a GA with missing metadata - very cool
3. Voted on it
4. Waited...
5. Transaction went through
6. Vote showed up in GA explorer as it should.

All tests passed

Loom video: 

https://www.loom.com/share/4ae8857b4e4040e7aed8625679b7636a?sid=1188f825-20a2-46cb-a979-29fd84a5da99

Closing this, as I understood that the bug was that Voting could not be accomplished, and now it can.

**Comment by m-i-k-e** [comment]
I'm re-opening this issue as the DRep registration failed when I tried it a second time. This issue was tested with a re-registration, and the failed registration was a new registration. Something is slightly incorrect it seems.

The above Loom video shows it working, but subsequently, the DRep registration fails, so I can't pass this in that case, as if I took the other path, it would not have worked.  https://www.loom.com/share/696c474dec6b4077a2ddb00c78296973?sid=8d009eba-0a89-45ab-abce-6f08eda3adfb

**Comment by m-i-k-e** [comment]
[misterDrep (2).jsonld.zip](https://github.com/user-attachments/files/15788102/misterDrep.2.jsonld.zip)
JSON file for this issue

**Comment by m-i-k-e** [comment]
https://raw.githubusercontent.com/m-i-k-e/meta_test/main/misterDrep%20(2).jsonld

**Comment by MSzalowski** [comment]
Tested on
1. Reregister
2. Declining the registration after successful validation and right after once again going through the flow
3. Going back through the flow and finally submitting the transaction

Everything seems to be working correctly.

@pmbinapps Could you please retest that issue?

**Comment by pmbinapps** [comment]
Confirming @MSzalowski,
OK - normal flow - for DRep - jam [recording](https://jam.dev/c/7036b746-ad06-43b7-a426-446b89a3e184)


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/a4b7cd1a-9934-4c60-bc6f-7917288f0d8a)


OK - declined flow and reregister - jam [recording](https://jam.dev/c/6c1ca58c-da4a-4932-9b3f-e70b10826607)
