### ISSUE TITLE
DRep detail data doesn't match entered data

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#908]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Become Drep
  2. Look at Drep list or drep detail page

## Actual behavior
Information on page does not match info entered when Drep created

## Expected behavior
Info should match

**Comment by pmbinapps** [comment]
Current data are mocked:


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/5cd3992f-24b7-4d35-9d30-0d93ffeb68f0)

**Comment by bosko-m** [comment]
Will be addressed once CIP-119 is resolved.

**Comment by bosko-m** [comment]
@l-br1 This might potentially go in a release as a known issue with appropriate message.

**Comment by m-i-k-e** [comment]
@l-br1 @bosko-m If we release this, we can watermark it as "Sample Data". I'm not a fan of this idea, I'd rather it worked, but if it can't:

<img width="657" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/a23eed4b-284a-4b25-b1c3-2c8791aeea8e">

**Comment by m-i-k-e** [comment]
@MSzalowski Could you please add some comments on the security of reading external files on the internet?

**Comment by MSzalowski** [comment]
Sure :+1:
We have many sources of truth around metadata-related things.
The best to depend on (from the technical side) is the db-sync which reflects the chain data - that is what we have currently for the governance actions.
We could fetch the metadata from the metadata url (provided by db-sync) on the frontend side but that results in potential security breach due to bypassing [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP).
However, we have the sub-backend allowing validation of the metadata (we get the metadata url and hash from db sync -> then we parse the metadata provided under this url and validate it against the hash).

We can take the metadata from that validation service (we've done it before when we had the similar issue with the gov action metadata missing in db-sync but that significantly increased loading time of the page (n of gov actions more number of requests)) and display them in both gov actions (as they are missing there now) and in DRep directory even though we don't have the CIP-119 active.

**Comment by bosko-m** [comment]
Thanks @MSzalowski , will have a decision the next day you are working.

**Comment by bosko-m** [comment]
@MSzalowski Please dont go with a workaround solution that doesnt imply CIP-119. According to @m-i-k-e suggestion, watermark the page with "Sample Data" text. @m-i-k-e is going to provide the design.
https://github.com/IntersectMBO/govtool/issues/908#issuecomment-2135247537

**Comment by m-i-k-e** [comment]
I've asked @kgrzonka to make some responsive designs in Figma

**Comment by m-i-k-e** [comment]
Responsive designs are in Figma, for "Sample Data", if needed. @MSzalowski 

https://www.figma.com/design/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?m=auto&node-id=14108-90052&t=gvTaOGLOeJmm7BiJ-1

**Comment by m-i-k-e** [comment]
Still using mocked data 4 Jun.

<img width="1503" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/63a6a4f3-aa0a-44a3-a81b-95194c4cc49f">

**Comment by pmbinapps** [comment]
OK NOW:
- data shown on Details page


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/e272ea19-3d62-4d74-a048-beff613c36c1)

Recheck on test-sancho...

**Comment by pmbinapps** [comment]
OK NOW
https://test-sanchonet.govtool.byron.network/connected/drep_directory/drep1pzuxy8ukuvffjyyrdp8sxkzp3z8r57z5q0jtgxhwu3a22t9ppel


![Image](https://github.com/IntersectMBO/govtool/assets/82152577/396d1a69-6624-4e77-a97e-bc82fabd4b83)

**Comment by m-i-k-e** [comment]
Cannot become DRep, so blocked for testing

**Comment by bosko-m** [comment]
@m-i-k-e Why cant you become DRep?

**Comment by m-i-k-e** [comment]
@bosko-m "Metadata not verified" error. See this issue: https://github.com/IntersectMBO/govtool/issues/1011

All DRep testing is blocked, as I can't become one.

**Comment by MSzalowski** [comment]
https://github.com/IntersectMBO/govtool/pull/1247 Unblocks this issue

**Comment by m-i-k-e** [comment]
This works now, closing as I can see the data.
