### ISSUE TITLE
Get "Do you want to abandon registration" modal when I have completed registration in DRep reg flow

### ISSUE THREAD

**Issue by m-i-k-e** [IntersectMBO/govtool#916]
## Context & versions
staging.sanchonet

## Steps to reproduce

  1. Go through Drep registration to the point where you have an external url for your metadata, paste it in, and click submit
  2. Dismiss the Modal
  3. Click "go back to dashboard"

## Actual behavior
You see a "Do you want to abandon registration" modal

## Expected behavior
You should just go back to the dashboard - the Drep is already registered, and the transaction is either completed or 'in progress'.

## Loom video https://www.loom.com/share/acde0a772b504c5cb77d8c2dfd4a3acf?sid=ac0b9ca2-609c-441c-a9be-42e907a9e805

**Comment by pmbinapps** [comment]
It looks like it's correct behaviour as the actual registration has not occurred yet - Data mach problem, so if 'Back to Dashboard' will cancel whole processes and user would lose entered data. 

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/b60d2218-bc01-44a2-b80d-434b54488a30)

Compare with screen [recording](https://jam.dev/c/afe663dd-23e7-4d58-9a36-197f2b3c1933) of whole flow

**Comment by m-i-k-e** [comment]
The first modal should not show up, as after the user clicks the submit button, they can't abandon registration. @pmbinapps Can you verify please?

<img width="729" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/64732cac-3cc2-4c3d-b379-79fad8713806">

**Comment by m-i-k-e** [comment]
@pmbinapps I don't understand why you have reassigned this to me. Can you elaborate?

**Comment by MSzalowski** [comment]
So the issue is, that after submitting the registration - validation of the metadata fails and we are reverted to the form to correct our data - **we should not be able to dismiss the registration**, is that correct @m-i-k-e?

However, if the validation fails, registration is not yet submitted - meaning that, transaction hasn't been sent, these data provided are not sent anywhere (on-chain, or off-chain), having said that - shouldn't the user be able to abandon the registration that still haven't occured?

**Comment by pmbinapps** [comment]
@m-i-k-e I believe that this confirmation modal correctly informs user that he/she will loose entered information even if DRep is already registered. Because he/she might want to updated his/her data. 



![Image](https://github.com/IntersectMBO/govtool/assets/82152577/7dc0e5da-35c0-401d-88d6-9d31443fd67f)


It is shown on every step of of DRep registration wizard which is reasonable as more and more effort has been made.

Anyway, here is [recording](https://jam.dev/c/56d78bca-596c-435f-b5a0-475004f9dc68) of all 'Back to dashboard' attempt son every step.
