### ISSUE TITLE
Dashboard - After becoming Direct Voter - Delegation card shows that Voting power is also delegated to a drepid

### ISSUE THREAD

**Issue by pmbinapps** [IntersectMBO/govtool#962]
To reproduce:

1. Become Sole Voter 

To reproduce fully confusing case:
1. Become DRep
2. Retire as Rep
3. Become a Sole Voter

Following screen is shown, suggesting that a delegation to some another DRep have made (actually its Dorec Voter - the DRrep id), additionally tooltip explains DRep Voting power meaning

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/375a019d-8c27-4210-aabf-ce019fbe6367)

[Design](https://www.figma.com/file/mJTBiUofLfb74Xc3W2U59o/Voltaire---GOV-TOOL?type=design&node-id=8754-62229&mode=design&t=eSMXTl8SzlTmXm4P-4):

![Image](https://github.com/IntersectMBO/govtool/assets/82152577/4511dbc5-9a30-4cb6-965f-3ff2deb2c69c)

There is no view for such case in designs.

**Comment by pmbinapps** [comment]
Some old related issue [here](https://github.com/IntersectMBO/govtool/issues/944)

**Comment by pmbinapps** [comment]
@m-i-k-e consider if to use the Figma design directly or you need some more work on this.

From discussion here looks like the current figma state should be [correct](https://private-user-images.githubusercontent.com/82152577/329065306-4511dbc5-9a30-4cb6-965f-3ff2deb2c69c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjQ1MjEsIm5iZiI6MTcxNTI2NDIyMSwicGF0aCI6Ii84MjE1MjU3Ny8zMjkwNjUzMDYtNDUxMWRiYzUtOWEzMC00Y2I2LTk2NWYtM2ZmMmRlYjJjNjljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE0MTcwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1N2YxMTFiZDJhZTAwMDlmZGExM2NhZTljZWE5NTQ3Y2NmYmRhMDgwNmE5YzQ3ODkyNGFjZTJhNzQ4ZjRlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RqrAtC86goDMmRmcZH5HL8cqGJIjm4NTGPJCxbMRWJo), 

the info under i tooltip is for DRep

**Comment by m-i-k-e** [comment]
@pmbinapps When I try to use your link for the picture in the comment above, I get an error: 
<img width="704" alt="image" src="https://github.com/IntersectMBO/govtool/assets/965789/2247acd3-2c2d-4f1a-809e-4c5325801323">
So I don't understand your comment.

**Comment by MSzalowski** [comment]
@m-i-k-e 

After registering as a Direct Voter we do the delegation to ourselves. These cards represents their own state meaning:
Direct voter card represents the current state of a Direct Voter registration.
Delegation card represents the current state of a current delegation.

Based on that these states represents the valid situation where:
* User was a DRep (so that Drep card shows the information about retirement).
* User is a Direct voter (displayed on a card)
* User delegated to some DRep (ourselves - Direct voter) - delegation card shows the current delegation.
* Tooltip is displayed (as still Direct voter as a DRep) - _should we change the copy of the voting power informing about being a Direct voter?_

**If we should restrict displaying the state on the delegation card (If I'm getting correct the issue reported by @pmbinapps) we need to directly specify the edge conditions between DRep, Direct voter, delegations and so on.**

**Comment by MSzalowski** [comment]
Moving to blocked until DRep/Direct voter egde conditions are clarified.

**Comment by MSzalowski** [comment]
Decision that happened during the meeting w @m-i-k-e @bosko-m @pmbinapps @Sworzen1 @akruk93 

When user is registered as a Direct voter - we should not display the delegation on the delegation card.

**Comment by MSzalowski** [comment]
Moved to seperate issue:
https://github.com/IntersectMBO/govtool/issues/1095

**Comment by pmbinapps** [comment]
Retested here: https://github.com/IntersectMBO/govtool/issues/1095 
Moving to stage.
